### PR TITLE
connection_config -> connection_db_config

### PR DESCRIPTION
**Pull request by quentindemetz**
DEPRECATION WARNING: connection_config is deprecated and will be removed from Rails 6.2 (Use connection_db_config instead)

### CODE REVIEW

**Comment by alekseyl** [comment]
OK, I'll look for the gem version branching

**Comment by tdeo** [comment]
Hello, I've added version branching to select either `connection_config` or `connection_db_config`

**Comment by alekseyl** [comment]
done

**Comment by tdeo** [comment]
Thanks for the reactivity !

**Comment by alekseyl** [comment]
Yep, merged to appreciate your work!
Thanx for using and participating in niceql :). 
Shipped connection / db_connection branching with new version 0.1.3

**Comment by jhirn** [comment]
Hello @alekseyl  

Unfortunately I'm having a bug with this due to `ActiveRecord::Base.try(:connection_db_config)` returning a speciality object `ActiveRecord::DatabaseConfigurations::HashConfig` which does not respond to dig. It doesn't even respond to `to_h` which is kind of a bummer but rather directly has the access methods on it. 

Screen Shot 2021-09-21 at 1 40 40 PM

I'm not sure what version of ActiveRecord this was introduced in, but I'm using version 6.1.4.1. I can't tell if `connection_db_config` has always returned this Object or not. The following suggestion works for me in my case, but I haven't had time to test against other versions of AR. 


```ruby
  def ar_using_pg_adapter?
      return false unless defined?(::ActiveRecord::Base)
      binding.pry
      config = ActiveRecord::Base.try(:connection_db_config) || ActiveRecord::Base.try(:connection_config)
      (config.try(:adapter) || config&.dig('adapter')) == 'postgresql'
  end
```

It's just to avoid deprecation warning for now so not urgent. If you'd like I can put together a PR for youu

**Comment by alekseyl** [comment]
fixed in version 0.2.0!

**Pull request merged**
